version: "2"

#services:
#  php:
#    container_name: slim_php
#    build:
#      context: .
#    image: nicholastanui/sme-kinyozi-engine
#    ports:
#      - '9000:9000'
#    volumes:
#      - .:/var/www/slim_app
#
#  nginx:
#    container_name: slim_nginx
#    image: nginx:stable-alpine
#    ports:
#      - '8080:80'
#    volumes:
#      - .:/var/www/slim_app
#      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
#    depends_on:
#      - php

services:
  web-frontend:
    build:
      context: .
      dockerfile: ./docker/web/frontend/Dockerfile
    ports:
      - '8080:80'
    depends_on:
      - web-backend


  web-backend:
    build:
      context: .
      dockerfile: ./docker/web/backend/Dockerfile
    ports:
    - '9000:9000'