name: Deployment Workflow
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    paths:
      - Dockerfile
      - docker-compose.yaml

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Code
        uses: actions/checkout@v2

      - name: Build Docker Images
        run: docker-compose create

      - name: Check Docker Image
        run: docker images -a

      - name: Check Docker Image2
        run: docker compose ps

#      - name: Build & push Docker image
#        uses: mr-smithers-excellent/docker-build-push@v5
#        with:
#          image: nicholastanui/sme-kinyozi
#          tags: latest
#          registry: docker.io
#          dockerfile: Dockerfile
#          username: ${{ secrets.DOCKER_USERNAME }}
#          password: ${{ secrets.DOCKER_PASSWORD }}

#      - name: testing kinyozi server ssh connection
#        uses: appleboy/ssh-action@master
#        with:
#          host: ${{ secrets.KINYOZI_HOST }}
#          username: ${{ secrets.KINYOZI_USERNAME }}
#          key: ${{ secrets.KINYOZI_SECRET}}
#          port: ${{ secrets.KINYOZI_PORT }}
#          script: |
